"""使用紀錄與回饋的 PostgreSQL 版（.env 設了 DATABASE_URL 時用，見 docs/adr/006）。

查詢語句與 SQLite 版（logs_repo.py）共用：送出前把 SQLite 的 ? 換成 psycopg 的 %s，
所以兩邊的 SQL 都不能出現字面上的 ? 或 %。
欄位與 SQLite 版相同，只有時間改成 TIMESTAMPTZ（每日 pg_dump、7 天清除照時間算）；
讀出來的時間轉回 ISO 8601（UTC）字串，呼叫端拿到的格式與 SQLite 版一樣。
"""

import sqlite3
from datetime import UTC, datetime
from pathlib import Path

import psycopg
from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool

from app.repositories import db
from app.repositories.logs_repo import LogsRepo

# 之後要加欄位：在這裡補 ALTER TABLE ... ADD COLUMN IF NOT EXISTS（正式版改用 Alembic migration）
_SCHEMA = """
CREATE TABLE IF NOT EXISTS uploads (
  image_id TEXT PRIMARY KEY, path TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS chat_logs (
  request_id TEXT PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL, artwork_id TEXT, part_id TEXT,
  question TEXT, strategy_requested TEXT, strategy_used TEXT, model TEXT, prompt_version TEXT,
  use_retrieval INTEGER, fallback INTEGER, retrieval_ms INTEGER, first_token_ms INTEGER,
  total_ms INTEGER, input_tokens INTEGER, output_tokens INTEGER, cost_twd DOUBLE PRECISION,
  egress_images INTEGER DEFAULT 0, egress_chunks INTEGER DEFAULT 0, egress_bytes BIGINT DEFAULT 0,
  answer TEXT
);
CREATE INDEX IF NOT EXISTS chat_logs_created_at ON chat_logs (created_at);
CREATE TABLE IF NOT EXISTS cad_logs (
  request_id TEXT PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL, job_id TEXT, part_id TEXT,
  image_id TEXT, strategy TEXT, model TEXT, ok INTEGER, error TEXT, iou DOUBLE PRECISION,
  iou_bbox DOUBLE PRECISION, scale DOUBLE PRECISION, scale_source TEXT,
  first_token_ms INTEGER, generation_ms INTEGER, exec_ms INTEGER, total_ms INTEGER,
  output_tokens INTEGER
);
CREATE INDEX IF NOT EXISTS cad_logs_created_at ON cad_logs (created_at);
CREATE TABLE IF NOT EXISTS feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, request_id TEXT NOT NULL,
  rating TEXT NOT NULL, note TEXT, created_at TIMESTAMPTZ NOT NULL
);
"""


def _iso(v):
    return v.astimezone(UTC).isoformat() if isinstance(v, datetime) else v


class PgLogsRepo(LogsRepo):
    def __init__(self, pool: ConnectionPool | None = None):
        self._pool = pool
        with self.pool.connection() as conn:
            conn.execute(_SCHEMA)

    @property
    def pool(self) -> ConnectionPool:
        return self._pool or db.get_pool()

    def _exec(self, sql: str, params: tuple = ()) -> list[dict]:
        # 時間參數是 ISO 字串：psycopg 送出的字串不帶型別，PostgreSQL 會照欄位轉成 TIMESTAMPTZ
        with self.pool.connection() as conn, conn.cursor(row_factory=dict_row) as cur:
            cur.execute(sql.replace("?", "%s"), params)
            rows = cur.fetchall() if cur.description else []
        return [{k: _iso(v) for k, v in r.items()} for r in rows]

    def ping(self) -> bool:
        try:
            return super().ping()
        except (db.DatabaseUnavailable, psycopg.Error):
            return False

    def import_sqlite(self, path: Path) -> dict[str, tuple[int, int]]:
        """把 SQLite 版（data/artrag.sqlite3）的紀錄搬進來，回傳各表（SQLite 筆數, 新寫入筆數）。

        改用 PostgreSQL 之前的紀錄（例如圖紙頁「最近的 3D 重建」讀的 cad_logs）要搬過來才看得到。
        主鍵已存在的略過；feedback 沒有自然主鍵，用 (request_id, created_at) 判斷搬過沒有。
        可以重複執行。"""
        src = sqlite3.connect(path.resolve().as_uri() + "?mode=ro", uri=True)  # 唯讀，不動原檔
        src.row_factory = sqlite3.Row
        result = {}
        try:
            with self.pool.connection() as conn:
                for table in ("uploads", "chat_logs", "cad_logs", "feedback"):
                    src_cols = [r["name"] for r in src.execute(f"PRAGMA table_info({table})")]
                    if not src_cols:  # 很舊的 SQLite 沒有這張表
                        continue
                    dst_cols = {
                        r[0]
                        for r in conn.execute(
                            "SELECT column_name FROM information_schema.columns"
                            " WHERE table_schema = 'public' AND table_name = %s",
                            (table,),
                        )
                    }
                    cols = [c for c in src_cols if c in dst_cols and c != "id"]
                    rows = [tuple(r) for r in src.execute(f"SELECT {', '.join(cols)} FROM {table}")]
                    total, conflict = len(rows), " ON CONFLICT DO NOTHING"
                    if table == "feedback":
                        seen = {
                            (rid, _iso(t))
                            for rid, t in conn.execute(
                                "SELECT request_id, created_at FROM feedback"
                            )
                        }
                        i, j = cols.index("request_id"), cols.index("created_at")
                        rows, conflict = [r for r in rows if (r[i], r[j]) not in seen], ""
                    count = f"SELECT count(*) FROM {table}"
                    before = conn.execute(count).fetchone()[0]
                    with conn.cursor() as cur:
                        cur.executemany(
                            f"INSERT INTO {table} ({', '.join(cols)})"
                            f" VALUES ({', '.join(['%s'] * len(cols))}){conflict}",
                            rows,
                        )
                    result[table] = (total, conn.execute(count).fetchone()[0] - before)
        finally:
            src.close()
        return result
