/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Image */
        post: operations["upload_image_api_v1_images_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images/{image_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image */
        get: operations["get_image_api_v1_images__image_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Image */
        post: operations["search_image_api_v1_search_image_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Text */
        get: operations["search_text_api_v1_search_text_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artworks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Artworks */
        get: operations["list_artworks_api_v1_artworks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artworks/{artwork_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artwork */
        get: operations["get_artwork_api_v1_artworks__artwork_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artworks/{artwork_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artwork Image */
        get: operations["get_artwork_image_api_v1_artworks__artwork_id__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Parts */
        get: operations["list_parts_api_v1_parts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parts/{part_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Part */
        get: operations["get_part_api_v1_parts__part_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parts/{part_id}/drawing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Part Drawing */
        get: operations["get_part_drawing_api_v1_parts__part_id__drawing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parts/{part_id}/model.{ext}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Part Model
         * @description 知識庫零件的標準 3D 模型（由 kb/cad/<id>.py 產生）：stl 給前端 3D 檢視、step 給 CAD 軟體。
         */
        get: operations["get_part_model_api_v1_parts__part_id__model__ext__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/drawing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Drawing */
        post: operations["search_drawing_api_v1_search_drawing_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/any": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Any
         * @description 不指定領域的以圖搜圖：先判斷是畫作還是工廠圖紙（領域路由），再做該領域的辨識。
         */
        post: operations["search_any_api_v1_search_any_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/parts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Parts */
        get: operations["search_parts_api_v1_search_parts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cad/reconstruct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reconstruct
         * @description 工廠圖紙 → Ortho2CAD 產生 CadQuery 程式碼 → 沙箱執行 → 3D 模型。
         */
        post: operations["reconstruct_api_v1_cad_reconstruct_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cad/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Cad Job
         * @description 已完成的 3D 重建（meta／result／done 三個事件的內容），給前端重看結果、不必重跑。
         */
        get: operations["get_cad_job_api_v1_cad_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parts/{part_id}/reconstructions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Part Reconstructions */
        get: operations["list_part_reconstructions_api_v1_parts__part_id__reconstructions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cad/jobs/{job_id}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cad File */
        get: operations["get_cad_file_api_v1_cad_jobs__job_id___name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Feedback */
        post: operations["feedback_api_v1_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eval/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Eval Runs */
        get: operations["eval_runs_api_v1_eval_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eval/cad-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cad Eval Runs
         * @description 工廠圖紙評估（make eval-cad）：圖紙辨識與 Ortho2CAD 3D 重建。
         */
        get: operations["cad_eval_runs_api_v1_eval_cad_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/outage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate Outage
         * @description 展示用：模擬主推論伺服器斷線，本地備援模型不受影響（DEMO_CONTROLS=false 時停用）。
         */
        post: operations["simulate_outage_api_v1_admin_outage_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnySearchResponse */
        AnySearchResponse: {
            /** Query Image Id */
            query_image_id: string;
            route: components["schemas"]["RouteInfo"];
            /** @description 判定為畫作時的辨識結果 */
            artwork_result: components["schemas"]["ImageSearchResponse"] | null;
            /** @description 判定為圖紙時的辨識結果 */
            drawing_result: components["schemas"]["DrawingSearchResponse"] | null;
            /** Latency Ms */
            latency_ms: number;
        };
        /** ArtworkDetail */
        ArtworkDetail: {
            /** Id */
            id: string;
            /** Source Id */
            source_id?: string | null;
            /** Title */
            title: {
                [key: string]: string;
            };
            /** Artist */
            artist: {
                [key: string]: string;
            };
            /** Date Text */
            date_text: string;
            /** Medium */
            medium?: string | null;
            /** Dimensions */
            dimensions?: string | null;
            /** Collection */
            collection: string;
            image: components["schemas"]["ArtworkImage"];
            /** Source Url */
            source_url: string;
            /** Descriptions */
            descriptions: components["schemas"]["Description"][];
            /**
             * Style Tags
             * @default []
             */
            style_tags: string[];
            /** Image Url */
            image_url: string;
            /** Thumb Url */
            thumb_url: string;
        };
        /** ArtworkImage */
        ArtworkImage: {
            /** Path */
            path: string;
            /** License */
            license: string;
            /** Attribution */
            attribution?: string | null;
            /** Source Url */
            source_url?: string | null;
        };
        /** ArtworkListResponse */
        ArtworkListResponse: {
            /** Kb Version */
            kb_version: string;
            /** Items */
            items: components["schemas"]["ArtworkSummary"][];
        };
        /** ArtworkSummary */
        ArtworkSummary: {
            /** Id */
            id: string;
            /** Title Zh */
            title_zh: string;
            /** Title En */
            title_en?: string | null;
            /** Artist Zh */
            artist_zh: string;
            /** Artist En */
            artist_en?: string | null;
            /** Date Text */
            date_text: string;
            /** Collection */
            collection: string;
            /** Image Url */
            image_url: string;
            /** Thumb Url */
            thumb_url: string;
            /**
             * Style Tags
             * @default []
             */
            style_tags: string[];
        };
        /** Body_upload_image_api_v1_images_post */
        Body_upload_image_api_v1_images_post: {
            /** File */
            file: string;
        };
        /** CadEvalRunsResponse */
        CadEvalRunsResponse: {
            /** Runs */
            runs: {
                [key: string]: unknown;
            }[];
        };
        /** CadJobListResponse */
        CadJobListResponse: {
            /** Items */
            items: components["schemas"]["CadJobRow"][];
        };
        /** CadJobRow */
        CadJobRow: {
            /** Job Id */
            job_id: string;
            /** Created At */
            created_at: string;
            /** Strategy */
            strategy: string;
            /** Model */
            model: string;
            /** Ok */
            ok: boolean;
            /** Iou */
            iou?: number | null;
            /** Iou Bbox */
            iou_bbox?: number | null;
            /** Total Ms */
            total_ms?: number | null;
        };
        /** CadJobSummary */
        CadJobSummary: {
            /** Meta */
            meta: {
                [key: string]: unknown;
            };
            /** Result */
            result: {
                [key: string]: unknown;
            };
            /** Done */
            done: {
                [key: string]: unknown;
            };
        };
        /** ChatRequest */
        ChatRequest: {
            /** Question */
            question: string;
            /** Artwork Id */
            artwork_id?: string | null;
            /**
             * Part Id
             * @description 工廠圖紙問答；與 artwork_id 擇一
             */
            part_id?: string | null;
            /** Image Id */
            image_id?: string | null;
            /**
             * Strategy
             * @default hybrid
             * @enum {string}
             */
            strategy: "hybrid" | "api_nokb" | "api_kb" | "lora" | "mock";
            /**
             * Use Retrieval
             * @default true
             */
            use_retrieval: boolean;
            /**
             * Allow Fallback
             * @default true
             */
            allow_fallback: boolean;
            /**
             * Rearrange
             * @description 檢索段落篩選（MIRA 的 Rearrange）；null＝依伺服器設定（預設關）
             */
            rearrange?: boolean | null;
        };
        /** Description */
        Description: {
            /** Lang */
            lang: string;
            /** Topic */
            topic?: string | null;
            /** Text */
            text: string;
            /** Source Url */
            source_url: string;
            /** License */
            license: string;
            /** Attribution */
            attribution?: string | null;
        };
        /** DrawingSearchHit */
        DrawingSearchHit: {
            part: components["schemas"]["PartSummary"];
            /**
             * Score
             * @description Chinese-CLIP 餘弦相似度
             */
            score: number;
            /**
             * Inliers
             * @description ORB 幾何驗證的 inlier 數；未驗證為 null
             */
            inliers: number | null;
            /**
             * Overlap
             * @description 拉正後的線條重合度（0–1）；未驗證為 null
             */
            overlap: number | null;
            /** Verified */
            verified: boolean;
        };
        /** DrawingSearchRequest */
        DrawingSearchRequest: {
            /** Image Id */
            image_id: string;
            /** Top K */
            top_k?: number | null;
        };
        /** DrawingSearchResponse */
        DrawingSearchResponse: {
            /** Query Image Id */
            query_image_id: string;
            /** Threshold */
            threshold: number;
            /** Min Inliers */
            min_inliers: number;
            /** Min Overlap */
            min_overlap: number;
            /** Matched */
            matched: boolean;
            /** Best Part Id */
            best_part_id: string | null;
            /** Latency Ms */
            latency_ms: number;
            /** Results */
            results: components["schemas"]["DrawingSearchHit"][];
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** EvalRun */
        EvalRun: {
            /** Run Id */
            run_id: string;
            /** Created At */
            created_at: string;
            /** Kb Version */
            kb_version: string;
            /** Prompt Version */
            prompt_version: string;
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
            /** By Strategy */
            by_strategy: {
                [key: string]: unknown;
            };
        };
        /** EvalRunsResponse */
        EvalRunsResponse: {
            /** Runs */
            runs: components["schemas"]["EvalRun"][];
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /** Request Id */
            request_id: string;
            /**
             * Rating
             * @enum {string}
             */
            rating: "up" | "down";
            /** Note */
            note?: string | null;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Db */
            db: boolean;
            /** Index Consistent */
            index_consistent: boolean;
            /** Index Problems */
            index_problems: string[];
            /** Kb Version */
            kb_version: string;
            /** Manifest */
            manifest: {
                [key: string]: unknown;
            };
            /** Strategies */
            strategies: {
                [key: string]: components["schemas"]["StrategyStatus"];
            };
            /** Llm Mode */
            llm_mode: string;
            /** Embed Mode */
            embed_mode: string;
            /** Allow Cloud */
            allow_cloud: boolean;
            /** Outage Simulated */
            outage_simulated: boolean;
            /** Demo Controls */
            demo_controls: boolean;
            /** Recent Chats */
            recent_chats: {
                [key: string]: unknown;
            }[];
            /**
             * Recent Cad
             * @default []
             */
            recent_cad: {
                [key: string]: unknown;
            }[];
        };
        /** ImageSearchHit */
        ImageSearchHit: {
            artwork: components["schemas"]["ArtworkSummary"];
            /**
             * Score
             * @description Chinese-CLIP 餘弦相似度
             */
            score: number;
            /**
             * Inliers
             * @description ORB 幾何驗證的 inlier 數；未驗證為 null
             */
            inliers: number | null;
            /** Verified */
            verified: boolean;
        };
        /** ImageSearchRequest */
        ImageSearchRequest: {
            /** Image Id */
            image_id: string;
            /** Top K */
            top_k?: number | null;
        };
        /** ImageSearchResponse */
        ImageSearchResponse: {
            /** Query Image Id */
            query_image_id: string;
            /** Threshold */
            threshold: number;
            /** Min Inliers */
            min_inliers: number;
            /** Matched */
            matched: boolean;
            /** Best Artwork Id */
            best_artwork_id: string | null;
            /** Latency Ms */
            latency_ms: number;
            /** Results */
            results: components["schemas"]["ImageSearchHit"][];
        };
        /** ImageUploadResponse */
        ImageUploadResponse: {
            /** Image Id */
            image_id: string;
            /** Width */
            width: number;
            /** Height */
            height: number;
        };
        /** OkResponse */
        OkResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
        };
        /** OutageRequest */
        OutageRequest: {
            /** Enabled */
            enabled: boolean;
        };
        /** PartDescription */
        PartDescription: {
            /** Topic */
            topic: string;
            /** Text */
            text: string;
            /** Source */
            source: string;
        };
        /** PartDetail */
        PartDetail: {
            /** Id */
            id: string;
            /** Part No */
            part_no: string;
            /** Drawing No */
            drawing_no: string;
            /** Revision */
            revision: string;
            /** Name */
            name: {
                [key: string]: string;
            };
            /** Category */
            category: string;
            /** Material */
            material: string;
            /** Density G Cm3 */
            density_g_cm3: number;
            /** Surface */
            surface?: string | null;
            /** Company */
            company: string;
            /** Owner */
            owner: string;
            /**
             * Confidentiality
             * @enum {string}
             */
            confidentiality: "公開" | "內部" | "機密";
            geometry: components["schemas"]["PartGeometry"];
            /** Descriptions */
            descriptions: components["schemas"]["PartDescription"][];
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /** Drawing Url */
            drawing_url: string;
            /** Thumb Url */
            thumb_url: string;
            /** Model Url */
            model_url: string;
            /** Step Url */
            step_url: string;
        };
        /** PartGeometry */
        PartGeometry: {
            /**
             * Width
             * @description X 方向外形尺寸（mm）
             */
            width: number;
            /**
             * Depth
             * @description Y 方向外形尺寸（mm）
             */
            depth: number;
            /**
             * Height
             * @description Z 方向外形尺寸（mm）
             */
            height: number;
            /** Volume Mm3 */
            volume_mm3: number;
            /**
             * Weight Kg
             * @description 標準模型體積 × 材料密度
             */
            weight_kg: number;
            /** Faces */
            faces: number;
        };
        /** PartListResponse */
        PartListResponse: {
            /** Kb Version */
            kb_version: string;
            /** Items */
            items: components["schemas"]["PartSummary"][];
        };
        /** PartSummary */
        PartSummary: {
            /** Id */
            id: string;
            /** Part No */
            part_no: string;
            /** Drawing No */
            drawing_no: string;
            /** Revision */
            revision: string;
            /** Name Zh */
            name_zh: string;
            /** Name En */
            name_en?: string | null;
            /** Category */
            category: string;
            /** Material */
            material: string;
            /**
             * Confidentiality
             * @enum {string}
             */
            confidentiality: "公開" | "內部" | "機密";
            geometry: components["schemas"]["PartGeometry"];
            /** Drawing Url */
            drawing_url: string;
            /** Thumb Url */
            thumb_url: string;
            /**
             * Model Url
             * @description 標準 3D 模型（STL）
             */
            model_url: string;
            /**
             * Tags
             * @default []
             */
            tags: string[];
        };
        /** PartTextSearchHit */
        PartTextSearchHit: {
            part: components["schemas"]["PartSummary"];
            /** Score */
            score: number;
            /** Topic */
            topic: string;
            /** Snippet */
            snippet: string;
        };
        /** PartTextSearchResponse */
        PartTextSearchResponse: {
            /** Query */
            query: string;
            /** Latency Ms */
            latency_ms: number;
            /** Results */
            results: components["schemas"]["PartTextSearchHit"][];
        };
        /** ReconstructRequest */
        ReconstructRequest: {
            /**
             * Part Id
             * @description 知識庫圖紙
             */
            part_id?: string | null;
            /**
             * Image Id
             * @description 上傳的圖紙照片；與 part_id 同時給代表照片已辨識為該圖紙
             */
            image_id?: string | null;
            /**
             * Strategy
             * @description ortho2cad＝主模型；hybrid＝未微調的 Qwen3-VL（對照組）
             * @default ortho2cad
             * @enum {string}
             */
            strategy: "ortho2cad" | "hybrid";
        };
        /**
         * RouteInfo
         * @description 領域路由（MMed-RAG 的領域辨識）：照片是畫作還是工廠圖紙
         */
        RouteInfo: {
            /**
             * Domain
             * @description art：畫作；mfg：工廠圖紙
             * @enum {string}
             */
            domain: "art" | "mfg";
            /**
             * Margin
             * @description 與圖紙原型的相似度 − 與畫作原型的相似度；> 0 偏向圖紙
             */
            margin: number;
            /**
             * Art Score
             * @description 與畫作原型（知識庫畫作 CLIP 向量的平均）的相似度
             */
            art_score: number | null;
            /**
             * Mfg Score
             * @description 與圖紙原型的相似度
             */
            mfg_score: number | null;
            /**
             * Min Margin
             * @description |margin| 小於此值視為不確定
             */
            min_margin: number;
            /**
             * Uncertain
             * @description 不確定時一律當圖紙（機密側）
             */
            uncertain: boolean;
        };
        /** StrategyStatus */
        StrategyStatus: {
            /** Label */
            label: string;
            /** Model */
            model: string;
            /** Available */
            available: boolean;
            /** Detail */
            detail: string;
        };
        /** TextSearchHit */
        TextSearchHit: {
            artwork: components["schemas"]["ArtworkSummary"];
            /** Score */
            score: number;
            /** Image Score */
            image_score: number;
            /** Text Score */
            text_score: number;
        };
        /** TextSearchResponse */
        TextSearchResponse: {
            /** Query */
            query: string;
            /** Latency Ms */
            latency_ms: number;
            /** Results */
            results: components["schemas"]["TextSearchHit"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_image_api_v1_images_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_image_api_v1_images_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageUploadResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_image_api_v1_images__image_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    search_image_api_v1_search_image_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageSearchResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    search_text_api_v1_search_text_get: {
        parameters: {
            query: {
                q: string;
                top_k?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TextSearchResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_artworks_api_v1_artworks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtworkListResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_artwork_api_v1_artworks__artwork_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artwork_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtworkDetail"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_artwork_image_api_v1_artworks__artwork_id__image_get: {
        parameters: {
            query?: {
                size?: string;
            };
            header?: never;
            path: {
                artwork_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    chat_api_v1_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description SSE：sources／token／done／error */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_parts_api_v1_parts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartListResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_part_api_v1_parts__part_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                part_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartDetail"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_part_drawing_api_v1_parts__part_id__drawing_get: {
        parameters: {
            query?: {
                size?: string;
            };
            header?: never;
            path: {
                part_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_part_model_api_v1_parts__part_id__model__ext__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                part_id: string;
                ext: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    search_drawing_api_v1_search_drawing_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DrawingSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DrawingSearchResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    search_any_api_v1_search_any_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnySearchResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    search_parts_api_v1_search_parts_get: {
        parameters: {
            query: {
                q: string;
                top_k?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartTextSearchResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reconstruct_api_v1_cad_reconstruct_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReconstructRequest"];
            };
        };
        responses: {
            /** @description SSE：meta／token／result／done／error（見 shared/sse_events.md） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_cad_job_api_v1_cad_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CadJobSummary"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_part_reconstructions_api_v1_parts__part_id__reconstructions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                part_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CadJobListResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_cad_file_api_v1_cad_jobs__job_id___name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    feedback_api_v1_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    eval_runs_api_v1_eval_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunsResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cad_eval_runs_api_v1_eval_cad_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CadEvalRunsResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    simulate_outage_api_v1_admin_outage_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
